version: '1'
services:
  discloneapi:
    build: .
    image: a25610/disclone-api:reloaded
    ports:
      - "5610:5610"
    environment:
      - ENCRYPTION_KEY=supermegasecret_
      - DB_PASSWORD=supermegapassword
    volumes:
      - ./logs:/App/logs
    profiles: ["prod"]
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    profiles: ["local"]
